# --- SonarCloud configuration ---
sonar.organization=renzoheads
sonar.projectKey=RenzoHeads_Deep-Learning-URLs-maliciosas-incrustadas-QR
sonar.projectName=Deep-Learning-URLs-maliciosas-incrustadas-QR
sonar.projectVersion=1.0

# Source paths
sonar.sources=android/app/src/main/java,backend/app
sonar.tests=android/app/src/test/java,backend/tests

# Language — multi-language project (Kotlin + Python)
sonar.language=kotlin,py

# Exclusions
sonar.exclusions=**/build/**,**/*.json,**/*.xml,**/*.pro,backend/api/**

# Kotlin specific
sonar.kotlin.coverage.jacoco.xmlReportPaths=android/app/build/reports/jacoco/**/*.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Branch
sonar.branch=main
