# ProGuard / R8 rules for QR Security Detector.

# ───────────────────────────────────────────────────────────────
# TFLite — Keep interpreter, model loader, and native bindings.
# ───────────────────────────────────────────────────────────────
-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.gpu.** { *; }
-keep class org.tensorflow.lite.nnapi.** { *; }
-keep class org.tensorflow.lite.support.** { *; }

# Do NOT strip TensorFlow Lite native libraries — the interpreter
# loads .so files at runtime and stripping causes unrecoverable crashes.
-keep class * {
    native <methods>;
}

# ───────────────────────────────────────────────────────────────
# ML Kit Barcode Scanning — keep model classes.
# ───────────────────────────────────────────────────────────────
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_barcode.** { *; }

# ───────────────────────────────────────────────────────────────
# ZXing fallback — keep core barcode decoding.
# ───────────────────────────────────────────────────────────────
-keep class com.google.zxing.** { *; }

# ───────────────────────────────────────────────────────────────
# kotlinx.serialization — keep serializers generated by the plugin.
# ───────────────────────────────────────────────────────────────
-keepattributes *Annotation*, InnerClasses, Signature, EnclosingMethod
-keep,includedescriptorclasses class com.qrsecurity.detector.**$$serializer { *; }
-keepclassmembers class com.qrsecurity.detector.** {
    *** Companion;
}
-keep class com.qrsecurity.detector.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# ───────────────────────────────────────────────────────────────
# Coroutines — keep internal debugging classes used at runtime.
# ───────────────────────────────────────────────────────────────
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# ─────────────────────────────────────────────────────────────────
# Jetpack Compose — keep annotation-related classes.
# ───────────────────────────────────────────────────────────────
-keep class androidx.compose.runtime.** { *; }

# ───────────────────────────────────────────────────────────────
# R8 missing-class suppressions — deps referenced at runtime by
# Play Asset Delivery / Tink but not on the compile classpath.
# Generated by R8 (see build/outputs/mapping/release/missing_rules.txt).
# ───────────────────────────────────────────────────────────────
-dontwarn com.google.android.gms.common.annotation.NoNullnessRewrite
-dontwarn com.google.api.client.http.GenericUrl
-dontwarn com.google.api.client.http.HttpHeaders
-dontwarn com.google.api.client.http.HttpRequest
-dontwarn com.google.api.client.http.HttpRequestFactory
-dontwarn com.google.api.client.http.HttpResponse
-dontwarn com.google.api.client.http.HttpTransport
-dontwarn com.google.api.client.http.javanet.NetHttpTransport$Builder
-dontwarn com.google.api.client.http.javanet.NetHttpTransport
-dontwarn org.joda.time.Instant

# ───────────────────────────────────────────────────────────────
# A-17 — Mantener clases @Serializable y sus serializadores generados
# ───────────────────────────────────────────────────────────────
# Con R8 fullMode (por defecto desde AGP 8.0), las clases anotadas con
# @Serializable que estan ANIDADAS dentro de una clase externa no
# @Serializable (p. ej. los DTO `RespuestaAuth`, `Escaneo`, `UrlBloqueada`,
# `Estadisticas`, `CategoriaDenuncia` y `Denuncia` anidados en
# `ClienteBackend`) se eliminan durante la minificacion, junto con sus
# `$$$serializer` internos. En runtime esto provoca
# `kotlinx.serialization.SerializationException` al invocar
# `Json.encodeToString` / `decodeFromString`.
#
# Lo mismo aplica a los DTO de paquete `com.qrsecurity.detector.datos.local.entidades`
# (`UrlBloqueadaEntity`, `EscaneoEntity`, `DenunciaEntity`) que se
# serializan a JSON por `SyncWorker` y `MediadorSincronizacion`.
#
# Estas reglas mantienen:
#   1. La clase y su `Companion` (poseedor del serializador).
#   2. Los `$$$serializer` internos generados por el plugin.
#   3. El accesor `$Companion` del campo Companion.
#   4. Los campos anotados con `@SerialName` (claves JSON personalizadas
#      que R8 podria eliminar si no ve el efecto de la anotacion sobre
#      un campo renombrado).
#
# Cobertura:
#   - `com.qrsecurity.detector.api.**`           -> DTO anidados en ClienteBackend.
#   - `com.qrsecurity.detector.datos.local.entidades.**` -> entidades serializables.
#   - `com.qrsecurity.detector.**$$serializer`  -> serializadores generados.
#   - `@Serializable com.qrsecurity.detector.**` -> red de seguridad para cualquier
#     futura clase @Serializable en cualquier subpaquete de la app.
-keep,allowobfuscation class com.qrsecurity.detector.**$$serializer { *; }
-keep,allowshrinking class com.qrsecurity.detector.api.** {
    *;
}
-keep class com.qrsecurity.detector.api.** { <fields>; }
-keepclassmembers class com.qrsecurity.detector.api.** {
    *** Companion;
}
-keepclasseswithmembers class com.qrsecurity.detector.api.** {
    kotlinx.serialization.KSerializer serializer(...);
}
-keep,allowshrinking class com.qrsecurity.detector.datos.local.entidades.** {
    *;
}
-keep class com.qrsecurity.detector.datos.local.entidades.** { <fields>; }
-keepclassmembers class com.qrsecurity.detector.datos.local.entidades.** {
    *** Companion;
}
-keepclasseswithmembers class com.qrsecurity.detector.datos.local.entidades.** {
    kotlinx.serialization.KSerializer serializer(...);
}
-keep @kotlinx.serialization.Serializable class com.qrsecurity.detector.** {
    *** Companion;
    *;
}
-keepclassmembers @kotlinx.serialization.Serializable class com.qrsecurity.detector.** {
    *** Companion;
    *** Companion$Companion;
}
-keepclasseswithmembers @kotlinx.serialization.Serializable class com.qrsecurity.detector.** {
    kotlinx.serialization.KSerializer serializer(...);
}
